bootstrap

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1019,9 +1019,11 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-msvcrt=<crt>     set which C run-time library to build against
   --with-gnu-ld           assume the C compiler uses GNU ld default=no
   --with-pic              try to use only PIC/non-PIC objects default=use both
   --with-bigendian        set endianness for architecture (default=auto)
+--with-suffix=string  specify library name suffix
 
 Some influential environment variables:
   CC          C compiler command
@@ -1395,7 +1397,6 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-
 ac_aux_dir=
 for ac_dir in cfg $srcdir/cfg; do
   if test -f $ac_dir/install-sh; then
@@ -1423,8 +1424,6 @@ ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 
 
 
-CYGWIN=
-export CYGWIN
 # Make sure we can run config.sub.
 $ac_config_sub sun4 >/dev/null 2>&1 ||
   { { echo "$as_me:$LINENO: error: cannot run $ac_config_sub" >&5
@@ -1508,6 +1507,11 @@ test -n "$target_alias" &&
     NONENONEs,x,x, &&
   program_prefix=${target_alias}-
 
+CYGWIN=
+export CYGWIN
+
+
+sim_ac_build_library=true
 # If the Microsoft Visual C++ cl.exe compiler is available, set us up for
 # compiling with it and to generate an MSWindows .dll file.
 
@@ -1542,6 +1546,94 @@ fi
 case $CXX in
 *wrapmsvc.exe)
   BUILD_WITH_MSVC=true
+
+    sim_ac_msvcrt_LDFLAGS=""
+sim_ac_msvcrt_LIBS=""
+
+
+# Check whether --with-msvcrt or --without-msvcrt was given.
+if test "${with_msvcrt+set}" = set; then
+  withval="$with_msvcrt"
+  case `echo "$withval" | tr "A-Z" "a-z"` in
+  default | singlethread-static | ml | /ml | libc | libc\.lib )
+    sim_ac_msvcrt=singlethread-static
+    sim_ac_msvcrt_CFLAGS="/ML"
+    sim_ac_msvcrt_CXXFLAGS="/ML"
+    ;;
+  default-debug | singlethread-static-debug | mld | /mld | libcd | libcd\.lib )
+    sim_ac_msvcrt=singlethread-static-debug
+    sim_ac_msvcrt_CFLAGS="/MLd"
+    sim_ac_msvcrt_CXXFLAGS="/MLd"
+    ;;
+  multithread-static | mt | /mt | libcmt | libcmt\.lib )
+    sim_ac_msvcrt=multithread-static
+    sim_ac_msvcrt_CFLAGS="/MT"
+    sim_ac_msvcrt_CXXFLAGS="/MT"
+    ;;
+  multithread-static-debug | mtd | /mtd | libcmtd | libcmtd\.lib )
+    sim_ac_msvcrt=multithread-static-debug
+    sim_ac_msvcrt_CFLAGS="/MTd"
+    sim_ac_msvcrt_CXXFLAGS="/MTd"
+    ;;
+  multithread-dynamic | md | /md | msvcrt | msvcrt\.lib )
+    sim_ac_msvcrt=multithread-dynamic
+    sim_ac_msvcrt_CFLAGS="/MD"
+    sim_ac_msvcrt_CXXFLAGS="/MD"
+    ;;
+  multithread-dynamic-debug | mdd | /mdd | msvcrtd | msvcrtd\.lib )
+    sim_ac_msvcrt=multithread-dynamic-debug
+    sim_ac_msvcrt_CFLAGS="/MDd"
+    sim_ac_msvcrt_CXXFLAGS="/MDd"
+    ;;
+  *)
+
+echo >&2 ""
+
+
+: ${sim_ac_message_file=$ac_aux_dir/errors.txt}
+if test -f $sim_ac_message_file; then
+  sim_ac_message="`sed -n -e '/^!invalid-msvcrt$/,/^!/ { /^!/ d; p; }' <$sim_ac_message_file`"
+  if test x"$sim_ac_message" = x""; then
+    { { echo "$as_me:$LINENO: error: no message named 'invalid-msvcrt' in '$sim_ac_message_file' - notify the $PACKAGE_NAME maintainer(s)" >&5
+echo "$as_me: error: no message named 'invalid-msvcrt' in '$sim_ac_message_file' - notify the $PACKAGE_NAME maintainer(s)" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    eval "echo >&2 \"$sim_ac_message\""
+  fi
+else
+  { { echo "$as_me:$LINENO: error: file '$sim_ac_message_file' not found - notify the $PACKAGE_NAME maintainer(s)" >&5
+echo "$as_me: error: file '$sim_ac_message_file' not found - notify the $PACKAGE_NAME maintainer(s)" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+
+echo >&2 ""
+{ { echo "$as_me:$LINENO: error: aborting" >&5
+echo "$as_me: error: aborting" >&2;}
+   { (exit 1); exit 1; }; }
+
+    ;;
+  esac
+else
+  sim_ac_msvcrt=singlethread-static
+fi;
+
+echo "$as_me:$LINENO: checking MSVC++ C library choice" >&5
+echo $ECHO_N "checking MSVC++ C library choice... $ECHO_C" >&6
+echo "$as_me:$LINENO: result: $sim_ac_msvcrt" >&5
+echo "${ECHO_T}$sim_ac_msvcrt" >&6
+
+
+      CPPFLAGS="$CPPFLAGS $sim_ac_msvcrt_CPPFLAGS"
+      CFLAGS="$CFLAGS $sim_ac_msvcrt_CFLAGS"
+      CXXFLAGS="$CXXFLAGS $sim_ac_msvcrt_CXXFLAGS"
+      LDFLAGS="$LDFLAGS $sim_ac_msvcrt_LDFLAGS"
+      LIBS="$LIBS $sim_ac_msvcrt_LIBS"
+      # sim_ac_msvcrt_LIBLIBS is set up at the end
+      # sim_ac_msvcrt_LIBLDFLAGS is set up at the end
+
+
 
   ;;
 *)
@@ -1581,6 +1673,8 @@ echo "$as_me: error: aborting" >&2;}
 esac
 
 fi
+
+
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -2925,11 +3019,6 @@ echo "$as_me:$LINENO: result: $am_cv_CC_dependencies_compiler_type" >&5
 echo "${ECHO_T}$am_cv_CC_dependencies_compiler_type" >&6
 CCDEPMODE="depmode=$am_cv_CC_dependencies_compiler_type"
 
-
-
-
-
-		    		    		    ac_config_headers="$ac_config_headers config.h"
 
 
 # Check whether --enable-static or --disable-static was given.
@@ -4409,7 +4498,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4412 "configure"' > conftest.$ac_ext
+  echo '#line 4501 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4945,7 +5034,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:4948: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5037: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6738,7 +6827,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6741 "configure"
+#line 6830 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6836,7 +6925,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6839 "configure"
+#line 6928 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7560,6 +7649,16 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 # Prevent multiple expansion
 
 
+
+
+
+if $BUILD_WITH_MSVC; then
+  BUILD_WITH_MSVC_TRUE=
+  BUILD_WITH_MSVC_FALSE='#'
+else
+  BUILD_WITH_MSVC_TRUE='#'
+  BUILD_WITH_MSVC_FALSE=
+fi
 
 PROFIT_CFLAGS=
 
@@ -8977,53 +9076,74 @@ fi
 # **************************************************************************
 
 
+# Check whether --with-suffix or --without-suffix was given.
+if test "${with_suffix+set}" = set; then
+  withval="$with_suffix"
+  SUFFIX=$withval
+else
+  SUFFIX=
+fi;
+
+
+
+
 
 case $enable_static in
-true | yes)  PROFIT_STATIC=true;;
-*)           PROFIT_STATIC=false;;
+true | yes)  PROFIT_STATIC=true ;;
+*)           PROFIT_STATIC=false ;;
 esac
 
 case $enable_shared in
-true | yes)  PROFIT_SHARED=true;;
-*)           PROFIT_SHARED=false;;
+true | yes)  PROFIT_SHARED=true ;;
+*)           PROFIT_SHARED=false ;;
 esac
 
 LIBFLAGS=
 
 
-if $BUILD_WITH_MSVC; then
-  if $PROFIT_STATIC; then
-    # static overrides shared
-    :
-  else
-    PROFIT_CFLAGS="$PROFIT_CFLAGS -DPROFIT_MAKE_DLL"
-    PROFIT_EXTRA_CPPFLAGS="$PROFIT_EXTRA_CPPFLAGS -DPROFIT_DLL"
-  fi
-
-  debugfile=`pwd`/src/profit${PROFIT_MAJOR_VERSION}.pdb
-  debugfile=`cygpath -w "$debugfile" | sed 's,\\\\,\\\\\\\\,g'`
-  if $PROFIT_STATIC; then
-    LIBFLAGS="-LIB"
-    LIBFLAGS="$LIBFLAGS /OUT:profit$PROFIT_MAJOR_VERSION.lib"
-    PROFIT_EXTRA_CPPFLAGS="-I$includedir"
-    PROFIT_EXTRA_LDFLAGS="-L$libdir"
-    PROFIT_EXTRA_LIBS=
-  else
-    LIBFLAGS="-DLL /INCREMENTAL:NO"
-    case $enable_symbols in
-    no | false)
-      LIBFLAGS="$LIBFLAGS /RELEASE"
-      ;;
-    *)
-      PROFIT_CFLAGS="/Fd$debugfile $PROFIT_CFLAGS"
-      LIBFLAGS="$LIBFLAGS /DEBUG /PDB:profit$PROFIT_MAJOR_VERSION.pdb"
-      ;;
-    esac
-    LIBFLAGS="$LIBFLAGS /OUT:profit$PROFIT_MAJOR_VERSION.dll"
+if $sim_ac_build_library; then
+  if $BUILD_WITH_MSVC; then
+    rm -f vc60.pdb;
+    LIBFLAGS="$LIBFLAGS $sim_ac_msvcrt_LIBLDFLAGS"
+    LIBS="$LIBS $sim_ac_msvcrt_LIBLIBS"
+    if $PROFIT_STATIC; then
+      # static overrides shared
+      :
+    else
+      PROFIT_CFLAGS="$PROFIT_CFLAGS -DPROFIT_MAKE_DLL"
+      PROFIT_EXTRA_CPPFLAGS="$PROFIT_EXTRA_CPPFLAGS -DPROFIT_DLL"
+    fi
+    debugfile=`pwd`/src/profit${PROFIT_MAJOR_VERSION}${SUFFIX}.pdb
+    debugfile=`cygpath -w "$debugfile" | sed 's,\\\\,\\\\\\\\,g'`
+    if $PROFIT_STATIC; then
+      LIBFLAGS="-LIB $LIBFLAGS"
+      LIBFLAGS="$LIBFLAGS /OUT:profit$PROFIT_MAJOR_VERSION$SUFFIX.lib"
+      PROFIT_EXTRA_CPPFLAGS="-I$includedir"
+      PROFIT_EXTRA_LDFLAGS="-L$libdir"
+      PROFIT_EXTRA_LIBS=
+    else
+      LIBFLAGS="-DLL /INCREMENTAL:NO $LIBFLAGS"
+      case $enable_symbols in
+      no | false)
+        LIBFLAGS="$LIBFLAGS /RELEASE"
+        ;;
+      *)
+        PROFIT_CFLAGS="/Fd$debugfile $PROFIT_CFLAGS"
+        LIBFLAGS="$LIBFLAGS /DEBUG /PDB:profit$PROFIT_MAJOR_VERSION$SUFFIX.pdb"
+        ;;
+      esac
+      LIBFLAGS="$LIBFLAGS /OUT:profit$PROFIT_MAJOR_VERSION$SUFFIX.dll"
+    fi
   fi
 fi
 
 # **************************************************************************
+
+
+
+
+		    		    		    ac_config_headers="$ac_config_headers include/config.h"
+
 
 ac_config_files="$ac_config_files Makefile src/Makefile src/util/Makefile src/nodes/Makefile include/Makefile include/profit/Makefile include/profit/util/Makefile include/profit/nodes/Makefile examples/Makefile examples/fltdump/Makefile examples/fltstrip/Makefile examples/fltnode/Makefile examples/flt2vrml/Makefile"
 
@@ -9524,7 +9644,7 @@ do
   "examples/fltnode/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/fltnode/Makefile" ;;
   "examples/flt2vrml/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/flt2vrml/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
-  "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
+  "include/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/config.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
@@ -9664,12 +9784,15 @@ s,@STRIP@,$STRIP,;t t
 s,@ac_ct_STRIP@,$ac_ct_STRIP,;t t
 s,@CPP@,$CPP,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
+s,@BUILD_WITH_MSVC_TRUE@,$BUILD_WITH_MSVC_TRUE,;t t
+s,@BUILD_WITH_MSVC_FALSE@,$BUILD_WITH_MSVC_FALSE,;t t
 s,@PROFIT_CFLAGS@,$PROFIT_CFLAGS,;t t
 s,@DSUFFIX@,$DSUFFIX,;t t
 s,@CXX@,$CXX,;t t
 s,@CXXFLAGS@,$CXXFLAGS,;t t
 s,@ac_ct_CXX@,$ac_ct_CXX,;t t
 s,@CXXDEPMODE@,$CXXDEPMODE,;t t
+s,@SUFFIX@,$SUFFIX,;t t
 s,@LIBFLAGS@,$LIBFLAGS,;t t
 CEOF
 
@@ -10088,8 +10211,8 @@ done; }
   fi
   # Run the commands associated with the file.
   case $ac_file in
-    config.h ) # update the timestamp
-echo timestamp >"./stamp-h1"
+    include/config.h ) # update the timestamp
+echo timestamp >"include/stamp-h1"
  ;;
   esac
 done
